server {
    server_name staging.artverse.idata.ro;
    access_log /home/staging/app/access.log;
    error_log /home/staging/app/error.log;

    location / {
        return 301 https://staging.vernis9.art$request_uri;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/staging.artverse.idata.ro/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/staging.artverse.idata.ro/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = staging.artverse.idata.ro) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name staging.artverse.idata.ro;
    access_log /home/staging/app/access.log;
    error_log /home/staging/app/error.log;
    return 404; # managed by Certbot
}
