#!/usr/bin/env node
/**
 * Decision log: one file per decision under specs/decisions/log/ (#808, ADR-0010).
 *
 *   node script/decision-log.mjs          list every entry as a table, newest first
 *   node script/decision-log.mjs --check  validate every entry; exit 1 on any problem
 *
 * No index is committed on purpose: a generated index would be regenerated by every PR
 * and conflict exactly as the old single table did. The directory is the index.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const LOG_DIR = "specs/decisions/log";
export const CATEGORIES = ["Architecture", "Security", "Process", "Infrastructure", "Product"];
const FILENAME = /^(\d{4}-\d{2}-\d{2})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$/;

export function parseEntry(name, text) {
  const problems = [];
  const m = name.match(FILENAME);
  if (!m) problems.push(`filename must be YYYY-MM-DD-<kebab-slug>.md`);
  const fm = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!fm) return { name, problems: [...problems, "missing frontmatter block"] };
  const meta = {};
  for (const line of fm[1].split("\n")) {
    const kv = line.match(/^([a-z]+):\s*(.*)$/);
    if (kv) meta[kv[1]] = kv[2].replace(/\s+#.*$/, "").trim();
  }
  for (const k of ["date", "title", "issue", "category"]) if (!meta[k]) problems.push(`frontmatter missing "${k}"`);
  if (meta.date && m && meta.date !== m[1]) problems.push(`date ${meta.date} does not match filename date ${m[1]}`);
  if (meta.issue && !/^\d+$/.test(meta.issue)) problems.push(`issue must be a bare number, got "${meta.issue}"`);
  if (meta.category && !CATEGORIES.includes(meta.category)) problems.push(`category must be one of ${CATEGORIES.join(", ")}`);
  const body = text.slice(fm[0].length).trim();
  if (body.length < 80) problems.push("body is too short to be a reasoned decision (< 80 chars)");
  return { name, ...meta, body, problems };
}

export function loadEntries(dir = LOG_DIR) {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort()
    .reverse()
    .map((f) => parseEntry(f, readFileSync(join(dir, f), "utf8")));
}

export function renderTable(entries) {
  const rows = entries.map((e) => `| ${e.date ?? "?"} | ${e.title ?? e.name} (#${e.issue ?? "?"}) | ${e.category ?? "?"} | \`${e.name}\` |`);
  return ["| Date | Decision | Category | File |", "|---|---|---|---|", ...rows].join("\n");
}

if (process.argv[1] && process.argv[1].endsWith("decision-log.mjs")) {
  const entries = loadEntries();
  if (process.argv.includes("--check")) {
    const bad = entries.filter((e) => e.problems.length);
    for (const e of bad) for (const p of e.problems) console.error(`${LOG_DIR}/${e.name}: ${p}`);
    console.log(`${entries.length} entr${entries.length === 1 ? "y" : "ies"}, ${bad.length} with problems`);
    process.exit(bad.length ? 1 : 0);
  }
  console.log(renderTable(entries));
}
